# Generated by Django 2.0.6 on 2018-06-15 11:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_soundclouduser_youtubeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='scope',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='tokenType',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
