# Generated by Django 2.0.6 on 2018-06-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_auto_20180615_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyuser',
            old_name='accessToken',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='spotifyuser',
            old_name='refreshToken',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='spotifyuser',
            old_name='tokenType',
            new_name='token_type',
        ),
    ]
