# Generated by Django 2.0.6 on 2018-06-15 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0005_auto_20180615_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='expires_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
